---

language: python
python: "2.7"

env:
  - ANSIBLE_ROLES_PATH=../

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y curl

install:
  - pip install ansible

script:
  - ansible-playbook -i localhost, tests/test.yml --syntax-check
  - ansible-playbook -i localhost, tests/test.yml --connection=local

